title: My Site
remote_theme: pages-themes/tactile
description: "Portfolio for work and school. [About](/about) • [Projects](/projects)"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
